#!/bin/sh
# audit_examples.sh — Build every raylib example with the Vulkan backend
# and record pass / fail / deferred status in docs/vulkan_example_matrix.md.
#
# Usage:
#   sh src/tools/audit_examples.sh
#
# Categorization:
#   PASS         Compiles and links against the Vulkan backend.
#                Visual/runtime correctness is verified separately by the
#                Task 45 visual-regression harness — link success only means
#                the symbol surface is satisfied (some Phase 5+ features may
#                be present as stubs).
#   DEFERRED     Compile fails with a reference to a known-deferred feature
#                (compute shaders, SSBOs, framebuffers, 3D models, etc.).
#                Tracked for later phases.
#   INCOMPATIBLE Example bypasses raylib (raw GLFW/OpenGL); not expected to
#                ever work with the Vulkan backend.
#   BUILD_FAIL   Compile fails for some other reason — needs investigation.
#
# Notes:
#   - We do NOT actually run each example (would need windowed display).
#     A separate visual-regression harness covers that.
#   - Logs land in build/example_audit/<example>.log.
set -u

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
OUT="$ROOT/docs/vulkan_example_matrix.md"
LOGDIR="$ROOT/build/example_audit"
mkdir -p "$LOGDIR"
mkdir -p "$(dirname "$OUT")"

cat > "$OUT" <<'HEADER'
# raylib Vulkan backend — example compatibility matrix

Auto-generated by `src/tools/audit_examples.sh`. Do not edit by hand.

Each row reports whether the example builds with `GRAPHICS=GRAPHICS_API_VULKAN`.

| Status       | Meaning |
|--------------|---------|
| PASS         | Compiles and links cleanly. Visual/runtime correctness not verified here (see Task 45's visual regression harness). Some Phase 5+ features are present as stubs, so link success can predate full functional support. |
| DEFERRED     | Compile fails because the example references a feature not yet implemented (3D models, render textures, compute shaders, SSBOs). Tracked for Phase 5+. |
| INCOMPATIBLE | Example bypasses raylib (raw GLFW/OpenGL demos in `others/`); not expected to ever work with the Vulkan backend. |
| BUILD_FAIL   | Compile fails for an unexpected reason. Check `build/example_audit/<name>.log`. |

| Example | Status | Notes |
|---------|--------|-------|
HEADER

CATEGORIES="core shapes textures text models shaders audio others"
TOTAL=0; PASS=0; DEFERRED=0; INCOMPATIBLE=0; BUILD_FAIL_N=0

cd "$ROOT/examples"

for dir in $CATEGORIES; do
    [ -d "$dir" ] || continue
    for c in "$dir"/*.c; do
        [ -f "$c" ] || continue
        name=$(basename "$c" .c)
        rel="$dir/$name"
        log="$LOGDIR/$name.log"
        TOTAL=$((TOTAL+1))

        # Try to build; capture stdout+stderr.
        rm -f "$dir/$name"
        if make "$rel" GRAPHICS=GRAPHICS_API_VULKAN >"$log" 2>&1; then
            status="PASS"; note="-"
            PASS=$((PASS+1))
        else
            # Incompatible-by-design heuristic: examples that bypass raylib
            # entirely (raw GLFW or OpenGL demos) can never work with the
            # Vulkan backend, regardless of phase.
            if grep -qE "GLFW/glfw3\.h|glBindBuffer|glUseProgram|glVertexAttribPointer" "$c" 2>/dev/null; then
                status="INCOMPATIBLE"; note="raw GLFW/OpenGL demo, not raylib"
                INCOMPATIBLE=$((INCOMPATIBLE+1))
            # Deferred-feature heuristics: look for symbols / functions that
            # belong to phases 5+.
            elif grep -qE "LoadModel|LoadModelFromMesh|UnloadModel|DrawModel|LoadRenderTexture|BeginTextureMode|BeginMode3D|UpdateCamera|rlLoadShaderProgramCompute|rlLoadShaderBuffer|LoadFramebuffer|GenMeshSphere|GenMeshCube|LoadVrStereoConfig" "$log"; then
                status="DEFERRED"; note="needs Phase 5+ feature"
                DEFERRED=$((DEFERRED+1))
            else
                status="BUILD_FAIL"; note="see build/example_audit/$name.log"
                BUILD_FAIL_N=$((BUILD_FAIL_N+1))
            fi
        fi
        printf "| %s | %s | %s |\n" "$rel" "$status" "$note" >> "$OUT"
    done
done

cat >> "$OUT" <<EOF

## Summary

| Metric | Count |
|--------|-------|
| Total examples | $TOTAL |
| PASS | $PASS |
| DEFERRED | $DEFERRED |
| INCOMPATIBLE | $INCOMPATIBLE |
| BUILD_FAIL | $BUILD_FAIL_N |
EOF

echo "Audit complete: $TOTAL examples → PASS=$PASS DEFERRED=$DEFERRED INCOMPATIBLE=$INCOMPATIBLE BUILD_FAIL=$BUILD_FAIL_N"
echo "Matrix: $OUT"
